site_name: 有度即时通
site_url: https://youdu.im
site_description: 有度即时通的帮助中心，包含：用户指南、管理员指南、开发者文档、产品文档以及知乎的技术文章链接。
site_author: xinda.im inc.

nav:
  - 帮助中心: index.md
  - 用户指南:
    - 用户指南: user/index.md
    - 登录:
      - Windows客户端: user/a01_00001.md
      - Mac客户端: user/a01_00002.md
      - Linux客户端: user/a01_00003.md
      - 手机客户端: user/a01_00004.md
      - 常见登录问题: user/a01_00005.md
    - 会话消息:
      - Windows客户端: user/b01_00001.md
      - Mac客户端: user/b01_00002.md
      - Linux客户端: user/b01_00003.md
      - 手机客户端: user/b01_00004.md
    - 通讯录:
      - 通讯录使用指南: user/c01_00001.md
    - 下载安装:
      - Windows客户端: user/e01_00001.md
      - Mac客户端: user/e01_00002.md
      - Linux客户端: user/e01_00003.md
      - 手机客户端: user/e01_00004.md
    - 其他:
      - 如何寻求帮助: user/f01_00001.md
    - 使用手册:
      - Windows客户端: user/g01_00001.md
      - Mac客户端: user/g01_00002.md
      - Linux客户端: user/g01_00003.md
      - 手机客户端: user/g01_00004.md
  - 管理员指南:
    - admin/index.md
  - 开发者文档:
    - api/index.md
  - 产品文档:
    - product/index.md
  - 知乎: https://www.zhihu.com/people/youdu.im/posts
  - 官网首页: https://youdu.im/

theme:
  name: material
  font: false
  language: zh
  favicon: assets/favicon.ico
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.tabs

extra_css:
  - assets/extra.css

use_directory_urls: false

markdown_extensions:
  - meta

plugins:
  - search

copyright: <a target="_blank" href="https://youdu.im/">珠海信达九州科技有限公司</a> &copy; 2020 xinda.im <a target="_blank" href="https://youdu.im/copyright/terms.html">服务协议</a> <a target="_blank" href="http://beian.miit.gov.cn/">粤ICP备15035175号</a>

