site_name: 有度即时通
site_url: https://youdu.im
site_description: 有度即时通的帮助中心，包含：用户指南、管理员指南、开发者文档、产品文档以及知乎的技术文章链接。
site_author: xinda.im inc.

nav:
  - 帮助中心: index.md
  - 用户指南:
    - 用户指南: user/index.md
    - 登录:
      - Windows客户端: user/a01_00001.md
      - Mac客户端: user/a01_00002.md
      - Linux客户端: user/a01_00003.md
      - 手机客户端: user/a01_00004.md
      - 常见登录问题: user/a01_00005.md
    - 会话消息:
      - Windows客户端: user/b01_00001.md
      - Mac客户端: user/b01_00002.md
      - Linux客户端: user/b01_00003.md
      - 手机客户端: user/b01_00004.md
    - 通讯录:
      - 通讯录使用指南: user/c01_00001.md
    - 下载安装:
      - Windows客户端: user/e01_00001.md
      - Mac客户端: user/e01_00002.md
      - Linux客户端: user/e01_00003.md
      - 手机客户端: user/e01_00004.md
    - 其他:
      - 如何寻求帮助: user/f01_00001.md
    - 使用手册:
      - Windows客户端: user/g01_00001.md
      - Mac客户端: user/g01_00002.md
      - Linux客户端: user/g01_00003.md
      - 手机客户端: user/g01_00004.md
  - 管理员指南:
    - admin/index.md
    - 安装部署:
        - 服务端安装:
            - 安装准备: admin/a01_00001.md
            - Windows服务端安装: admin/a01_00002.md
            - Linux服务端安装: admin/a01_00003.md
            - 防火墙策略: admin/a01_00004.md
            - 导入License授权: admin/a01_00005.md
        - 服务端升级:
            - 升级前准备: admin/a01_00006.md
            - Windows服务端升级: admin/a01_00007.md
            - Linux服务端升级: admin/a01_00008.md
        - MySQL独立部署:
            - Windows版安装: admin/a01_00009.md
            - Windows迁移数据库: admin/a01_00010.md
            - Linux版安装: admin/a01_00011.md
            - Linux迁移数据库: admin/a01_00012.md
        - 文件服务独立部署:
            - 安装准备: admin/a01_00013.md
            - 主服务配置: admin/a01_00014.md
            - 文件服务配置: admin/a01_00015.md
        - 代理服务独立部署:
            - 安装准备: admin/a01_00016.md
            - 代理服务配置: admin/a01_00017.md
        - 推送服务独立部署:
            - 安装准备: admin/a01_00018.md
            - 主服务器配置: admin/a01_00019.md
            - 推送服务配置: admin/a01_00020.md
    - 增值服务:
        - 消息审计插件:
            - 安装准备: admin/e01_00001.md
            - Windows版安装: admin/e01_00002.md
            - Linux版安装: admin/e01_00003.md
            - 补充说明: admin/e01_00004.md
    - 数据管理:
        - 自动备份:
            - 备份说明: admin/f01_00001.md
            - Windows服务端备份恢复数据: admin/f01_00002.md
            - Linux服务端备份恢复数据: admin/f01_00003.md
        - 数据迁移:
            - 迁移准备: admin/f01_00004.md
            - 备份关键数据: admin/f01_00005.md
            - Windows旧服务器导出: admin/f01_00006.md
            - Windows新服务器导入: admin/f01_00007.md
            - Linux旧服务器导出: admin/f01_00008.md
            - Linux新服务器导入: admin/f01_00009.md
            - 迁移完成的后续事项: admin/f01_00010.md
    - RTX手机版:
        - 部署须知: admin/g01_00001.md
        - 部署RTX手机版: admin/g01_00002.md
        - 云版切换到本地部署版: admin/g01_00003.md
        - RTX升级至有度即时通: admin/g01_00004.md


  - 开发者文档:
    - api/index.md
    - 快速入门:
        - 概述: api/a01_00001.md
        - 简易教程:
            - 集成SDK: api/a01_00002.md
            - 调用SDK发送系统消息: api/a01_00003.md
    - 集成案例:
        - 开发说明:
            - 概述: api/b01_00001.md
            - 获取开发所需参数: api/b01_00002.md
        - 系统消息:
            - 概述: api/b01_00003.md
            - 发送系统消息: api/b01_00004.md
        - 单点登录:
            - 概述: api/b01_00005.md
            - 单点登录到第三方系统:
                - 流程说明: api/b01_00006.md
                - 验证Token: api/b01_00007.md
                - 特殊情况: api/b01_00008.md
            - 单点登录到有度:
                - 开发准备: api/b01_00009.md
                - Token获取接口: api/b01_00010.md
                - 客户端登录: api/b01_00011.md
                - 登录示例代码: api/b01_00012.md
                - 开发配置: api/b01_00013.md
        - 邮件集成:
            - 概述: api/b01_00014.md
            - 发送邮件消息: api/b01_00015.md
        - 短信网关:
            - 概述: api/b01_00016.md
            - 短信网关调试说明: api/b01_00017.md
            - 集成开发: api/b01_00018.md
        - 内部公众号:
            - 概述: api/b01_00019.md
            - 发送图文消息: api/b01_00020.md
        - 应用机器人:
            - 概述: api/b01_00021.md
            - 使用管理后台指南: api/b01_00022.md
            - 使用应用消息集成:
                - 概述: api/b01_00023.md
                - 应用消息回调: api/b01_00024.md
                - 发送应用消息: api/b01_00025.md
        - 消息审计:
            - 概述: api/b01_00026.md
            - 开发集成: api/b01_00027.md
        - 组织架构同步:
            - 概述: api/b01_00028.md
            - 部门管理:
                - 创建部门: api/b01_00029.md
                - 更新部门: api/b01_00030.md
                - 删除部门: api/b01_00031.md
                - 获取部门列表: api/b01_00032.md
                - 获取部门ID: api/b01_00033.md
            - 用户管理:
                - 创建用户: api/b01_00034.md
                - 更新用户: api/b01_00035.md
                - 删除用户: api/b01_00036.md
                - 批量删除用户: api/b01_00037.md
                - 获取用户信息: api/b01_00038.md
                - 获取部门用户及信息: api/b01_00039.md
                - 用户头像: api/b01_00040.md
            - 全量覆盖: api/b01_00041.md
        - 第三方认证:
            - 概述: api/b01_00042.md
            - 设置认证信息: api/b01_00043.md
            - 认证回调: api/b01_00044.md
        - 动态建群:
            - 概述: api/b01_00045.md
            - 创建群: api/b01_00046.md
            - 删除群: api/b01_00047.md
            - 修改群名称: api/b01_00048.md
            - 查看群信息: api/b01_00049.md
            - 群列表: api/b01_00050.md
            - 添加群成员: api/b01_00051.md
            - 删除群成员: api/b01_00052.md
            - 查询用户是否为群成员: api/b01_00053.md
        - 企业门户:
            - 概述: api/b01_00054.md
            - 浏览器弹窗: api/b01_00055.md
        - 代办角标: api/b01_00056.md
        - 扫码登录: api/b01_00057.md
    - 服务端API:
        - 企业应用开发流程:
            - 说明: api/c01_00001.md
            - 常见的集成模型: api/c01_00002.md
            - 应用开发流程概述: api/c01_00003.md
        - 全局说明:
            - 简要说明: api/c01_00004.md
            - 主动调用: api/c01_00005.md
            - 消息回调: api/c01_00006.md
            - 加解密说明: api/c01_00007.md
            - 获取accessToken: api/c01_00008.md
        - 全局状态码: api/c01_00009.md
        - 发送应用消息:
            - 说明: api/c01_00010.md
            - 消息类型和数据格式: api/c01_00011.md
        - 应用回复回调:
            - 说明: api/c01_00012.md
            - 回调消息类型和数据格式: api/c01_00013.md
        - 应用通知: api/c01_00014.md
        - 应用弹窗: api/c01_00015.md
        - 会话管理:
            - 说明: api/c01_00016.md
            - 创建会话: api/c01_00017.md
            - 获取会话: api/c01_00018.md
            - 修改会话: api/c01_00019.md
        - 发送会话消息:
            - 说明: api/c01_00020.md
            - 消息类型和数据格式: api/c01_00021.md
        - 会话消息回调:
            - 说明: api/c01_00022.md
            - 回调消息类型和数据格式: api/c01_00023.md
        - 会话消息数据下载:
            - 说明: api/c01_00024.md
            - 下载消息数据: api/c01_00025.md
            - 消息数据格式: api/c01_00026.md
            - 第三方接口处理响应: api/c01_00027.md
        - 单点登录: api/c01_00028.md
        - 素材管理:
            - 说明: api/c01_00029.md
            - 上传素材文件: api/c01_00030.md
            - 下载素材文件: api/c01_00031.md
            - 查看素材文件信息: api/c01_00032.md
        - 部门管理:
            - 创建部门: api/c01_00033.md
            - 更新部门: api/c01_00034.md
            - 删除部门: api/c01_00035.md
            - 获取部门列表: api/c01_00036.md
            - 获取部门ID: api/c01_00037.md
        - 用户管理:
            - 创建用户: api/c01_00038.md
            - 更新用户: api/c01_00039.md
            - 更新用户部门职务信息: api/c01_00040.md
            - 删除用户: api/c01_00041.md
            - 批量删除用户: api/c01_00042.md
            - 获取用户信息: api/c01_00043.md
            - 获取部门用户: api/c01_00044.md
            - 获取部门用户详细信息: api/c01_00045.md
            - 设置认证信息: api/c01_00046.md
            - 认证回调: api/c01_00047.md
            - 设置用户头像: api/c01_00048.md
            - 获取用户头像: api/c01_00049.md
        - 全量覆盖:
            - 说明: api/c01_00050.md
            - 全量覆盖: api/c01_00051.md
            - 获得全量覆盖结果: api/c01_00052.md
            - 全量覆盖完成通知: api/c01_00053.md
        - 群管理:
            - 创建群: api/c01_00054.md
            - 删除群: api/c01_00055.md
            - 修改群名称: api/c01_00056.md
            - 查看群信息: api/c01_00057.md
            - 群列表: api/c01_00058.md
            - 添加群成员: api/c01_00059.md
            - 删除群成员: api/c01_00060.md
            - 查询用户是否为群成员: api/c01_00061.md
    - 客户端API:
        - 开发说明: api/d01_00001.md
        - 扫一扫: api/d01_00002.md
        - 组织架构:
            - 获取身份token: api/d01_00003.md
        - 右上角按钮（Web-View）: api/d01_00004.md
        - 文件处理:
            - 图片: api/d01_00005.md
        - 设备信息:
            - 获取设备id: api/d01_00006.md
            - 获取wifibssid: api/d01_00007.md
            - 获取定位: api/d01_00008.md
    - 服务端SDK:
        - 基础设置: api/e01_00001.md
        - Java SDK开发指南: api/e01_00002.md
        - PHP SDK开发指南: api/e01_00003.md
        - Python SDK开发指南: api/e01_00004.md
        - C# SDK开发指南: api/e01_00005.md
        - Golang SDK开发指南: api/e01_00006.md
        - C++ SDK开发指南: api/e01_00007.md
        - SDK下载: api/e01_00008.md
  - 知乎: https://www.zhihu.com/people/youdu.im/posts
  - 官网首页: https://youdu.im/

theme:
  name: material
  font: false
  language: zh
  favicon: assets/favicon.ico
  logo: assets/logo.png
  head_logo: assets/head_logo.png
  custom_dir: overrides
  features:
    - navigation.tabs

extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js

use_directory_urls: false

markdown_extensions:
  - meta

plugins:
  - search

copyright: <a target="_blank" href="https://youdu.im/">珠海信达九州科技有限公司</a> &copy; 2020 xinda.im <a target="_blank" href="https://youdu.im/copyright/terms.html">服务协议</a> <a target="_blank" href="http://beian.miit.gov.cn/">粤ICP备15035175号</a>

