site_name: 有度即时通
site_url: https://youdu.im
site_description: 有度即时通的帮助中心，包含：用户指南、管理员指南、开发者文档、产品文档以及知乎的技术文章链接。
site_author: xinda.im inc.
repo_url: https://github.com/youduim/youdu-doc
edit_uri: edit/inner/docs/

nav:
  - 帮助中心: index.md
  - 用户指南:
    - 用户指南: user/index.md
    - 登录:
      - Windows客户端: user/a01_00001.md
      - Mac客户端: user/a01_00002.md
      - Linux客户端: user/a01_00003.md
      - 手机客户端: user/a01_00004.md
      - 常见登录问题: user/a01_00005.md
    - 会话消息:
      - Windows客户端: user/b01_00001.md
      - Mac客户端: user/b01_00002.md
      - Linux客户端: user/b01_00003.md
      - 手机客户端: user/b01_00004.md
      - 问题答疑: user/b01_00005.md
    - 通讯录:
      - 通讯录使用指南: user/c01_00001.md
      - 问题答疑: user/c01_00002.md
    - 下载安装:
      - Windows客户端: user/e01_00001.md
      - Mac客户端: user/e01_00002.md
      - Linux客户端: user/e01_00003.md
      - 手机客户端: user/e01_00004.md
    - 其他:
      - 如何寻求帮助: user/f01_00001.md
    - 使用手册:
      - Windows客户端: user/g01_00001.md
      - Mac客户端: user/g01_00002.md
      - Linux客户端: user/g01_00003.md
      - 手机客户端: user/g01_00004.md
  - 管理员指南:
    - admin/index.md
    - 安装部署:
        - 服务端安装:
            - 安装准备: admin/a01_00001.md
            - 【推荐】Docker:
                - Docker环境准备: admin/a01_00021.md
                - Docker使用手册: admin/a01_00022.md
                - 有度服务端安装: admin/a01_00023.md
                - Portainer容器管理平台: admin/a01_00024.md
            - Windows: admin/a01_00002.md
            - Linux: admin/a01_00003.md
            - 防火墙策略: admin/a01_00004.md
            - 导入License授权: admin/a01_00005.md
        - 服务端升级:
            - 升级前准备: admin/a01_00006.md
            - Windows服务端升级: admin/a01_00007.md
            - 【推荐】Linux二进制升级至Docker: admin/a01_00025.md
            - Linux二进制升级: admin/a01_00008.md
        - MySQL独立部署:
            - Windows版安装: admin/a01_00009.md
            - Windows迁移数据库: admin/a01_00010.md
            - Linux版安装: admin/a01_00011.md
            - Linux迁移数据库: admin/a01_00012.md
        - 文件服务独立部署:
            - 安装准备: admin/a01_00013.md
            - 主服务配置: admin/a01_00014.md
            - 文件服务配置: admin/a01_00015.md
        - 代理服务独立部署:
            - 安装准备: admin/a01_00016.md
            - 代理服务配置: admin/a01_00017.md
        - 推送服务独立部署:
            - 安装准备: admin/a01_00018.md
            - 主服务器配置: admin/a01_00019.md
            - 推送服务配置: admin/a01_00020.md
    - 拓展插件:
        - 服务监控系统（APM）:
            - APM系统部署: admin/a01_00026.md
    - 增值服务:
        - 消息审计插件:
            - 安装准备: admin/e01_00001.md
            - Windows版安装: admin/e01_00002.md
            - Linux版安装: admin/e01_00003.md
            - 补充说明: admin/e01_00004.md
            - 消息审计插件的迁移准备: admin/e01_00005.md
            - Windows版导出导入: admin/e01_00006.md
            - Linux版导出导入: admin/e01_00007.md
    - 数据管理:
        - 自动备份:
            - 备份说明: admin/f01_00001.md
            - Windows服务端备份恢复数据: admin/f01_00002.md
            - Linux服务端备份恢复数据: admin/f01_00003.md
        - 数据迁移:
            - 迁移准备: admin/f01_00004.md
            - 备份关键数据: admin/f01_00005.md
            - Windows旧服务器导出: admin/f01_00006.md
            - Windows新服务器导入: admin/f01_00007.md
            - Linux旧服务器导出: admin/f01_00008.md
            - Linux新服务器导入: admin/f01_00009.md
            - 迁移完成的后续事项: admin/f01_00010.md
    - RTX手机版:
        - RTX插件介绍: admin/g01_00001.md
        - 本地部署版安装指南（一）: admin/g01_00002.md
        - 本地部署版安装指南（二）: admin/g01_00003.md
        - 云版免费版安装指南: admin/g01_00004.md
        - 云免费版升级本地部署版: admin/g01_00005.md
        - 并行和独立运行的说明: admin/g01_00006.md
        - RTX全面切换至有度: admin/g01_00007.md
    - 问题答疑:
        - 授权和商务咨询: admin/h01_00002.md
        - 管理后台访问: admin/h01_00001.md
        - 防火墙端口开放: admin/h01_00003.md
        - 有度对外端口修改: admin/h01_00004.md
        - 有度开启网络带宽限流: admin/h01_00005.md
        - 客户端答疑: admin/h01_00006.md
        - 问题排查思路: admin/h01_00007.md
        - 登录问题: admin/h01_00008.md
        - 会话和消息: admin/h01_00010.md
        - 组织架构、账号和认证: admin/h01_00009.md
        - 文件传输、群空间和网盘: admin/h01_00011.md
    - 功能逻辑 :
        - 客户端登录: admin/i01_00001.md
        - 第三方认证: admin/i01_00002.md
        - 用户在线状态: admin/i01_00003.md
        - 客户端组织架构同步: admin/i01_00004.md
        - 有度消息收发: admin/i01_00005.md
        - 消息通知: admin/i01_00006.md
        - 消息多终端漫游: admin/i01_00007.md
        - 回执消息: admin/i01_00008.md
        - 文件传输: admin/i01_00009.md
        - 客户端数据存储: admin/i01_00010.md
        - 群空间和网盘: admin/i01_00011.md
        - 音视频功能说明: admin/i01_00012.md
        - 远程控制: admin/i01_00013.md
        - 考勤打卡: admin/i01_00014.md
        - 客户端升级: admin/i01_00015.md
        - 服务端数据存储位置: admin/i01_00016.md
        - 文件服务数据传输逻辑: admin/i01_00017.md
        - 第三方系统组织架构同步: admin/i01_00018.md
        - 企业集群: admin/i01_00019.md

  - 开发者文档:
    - api/index.md
    - 典型应用场景:
      - 概述: api/b01_00001.md
      - 组织架构同步:
        - 概述: api/b01_00012.md
        - 部门管理: api/b01_00013.md
        - 用户管理: api/b01_00014.md
        - 全量覆盖: api/b01_00016.md
      - 第三方认证: api/b01_00015.md
      - 扫码登录: api/b01_00018.md
      - 动态建群: api/b01_00017.md
      - 系统通知: api/b01_00002.md
      - 单点登录:
        - 单点登录到第三方系统: api/b01_00003.md
        - 单点登录到有度: api/b01_00004.md
      - 邮件集成: api/b01_00005.md
      - 短信网关: api/b01_00006.md
      - 客户端弹窗: api/b01_00007.md
      - 应用机器人: api/b01_00008.md
      - 代办角标: api/b01_00009.md
      - 内部公众号: api/b01_00010.md
      - 消息审计: api/b01_00011.md

    - 服务端开发指南:
      - 开发前必读: api/a01_00001.md
      - 全局状态码: api/a01_00009.md
      - SDK下载: api/a01_00002.md
      - SDK集成:
        - Java: api/a01_00003.md
        - PHP: api/a01_00004.md
        - Python: api/a01_00005.md
        - C#: api/a01_00006.md
        - Go: api/a01_00007.md
        - C++: api/a01_00008.md

    - 服务端API清单:
        - 开发流程: api/c01_00001.md
        - 全局说明（必读）: api/c01_00002.md
        - 企业应用:
            - 发送应用消息: api/c01_00003.md
            - 应用消息回调: api/c01_00004.md
            - 设置角标: api/c01_00005.md
            - 发送弹窗消息: api/c01_00006.md
        - 单点登录: api/c01_00007.md
        - 会话管理: api/c01_00008.md
        - 会话消息:
            - 发送消息: api/c01_00009.md
            - 消息回调: api/c01_00010.md
        - 自定义菜单: api/c01_00011.md
        - 企业通讯录:
            - 部门管理: api/c01_00012.md
            - 用户管理: api/c01_00013.md
            - 第三方认证: api/c01_00014.md
            - 群管理: api/c01_00015.md
            - 全量覆盖: api/c01_00016.md
        - 素材管理: api/c01_00017.md

    - 移动端SDK:
        - 开发说明: api/d01_00001.md
        - 扫一扫: api/d01_00002.md
        - 组织架构:
            - 获取身份token: api/d01_00003.md
        - 右上角按钮（Web-View）: api/d01_00004.md
        - 文件处理:
            - 图片: api/d01_00005.md
        - 设备信息:
            - 获取设备id: api/d01_00006.md
            - 获取wifibssid: api/d01_00007.md
            - 获取定位: api/d01_00008.md


  - 知乎: https://www.zhihu.com/people/youdu.im/posts
  - 官网首页: https://youdu.im/

theme:
  name: material
  font: false
  language: zh
  favicon: assets/favicon.ico
  logo: assets/logo.png
  head_logo: assets/head_logo.png
  custom_dir: overrides
  features:
    - navigation.tabs

extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js

use_directory_urls: false

markdown_extensions:
  - meta

plugins:
  - search

copyright: <a target="_blank" href="https://youdu.im/">珠海信达九州科技有限公司</a> &copy; 2020 xinda.im <a target="_blank" href="https://youdu.im/copyright/terms.html">服务协议</a> <a target="_blank" href="http://beian.miit.gov.cn/">粤ICP备15035175号</a>

